runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
  
env_variables:
  DEV_SERVER_DOMAIN: "www.darkmane.me"
  DARKMANE_DARKMANE_ME: "www.darkmane.me"
  DARKMANE_ME: "www.darkmane.me"
  GW2CRAFT_DARKMANE_ME: "gw2-craft.darkmane.me"
